SelfCare/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SelfCare.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

SelfCare/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using SelfCare.Models;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace SelfCare.Pages
{
    public class IndexModel : PageModel
    {
        private readonly SelfCareContext _selfcareContext;
        public List<Note> Notes { get; set; }
        public List<User> Users { get; set; }

        public IndexModel(SelfCareContext selfcareContext)
        {
            _selfcareContext = selfcareContext;

        }


        public IActionResult OnGetPartial()
        {

            Notes = _selfcareContext.Notes.ToList();
            return new PartialViewResult
            {
                ViewName = "_NoteTablePartial",
                ViewData = new ViewDataDictionary<List<Note>>(ViewData, Notes)
            };

        }

        public void OnGet()
        {
        }
    }
}

SelfCare/Pages/Signup.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SelfCare.Models;
using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Metrics;

namespace SelfCare.Pages
{
    [BindProperties]
    public class SignupModel : PageModel
    {
        [Required]
        [EmailAddress(ErrorMessage = "Must be a valid email")]
        public string Email { get; set; }
        [Required]
        public string Username { get; set; }
        [Required]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$", ErrorMessage = "Password must contain at least one lowercase letter, one uppercase letter, and one integer.")]
        public string Password { get; set; }
        [Required]
        public string ConfirmPassword { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        public Guid? PractitionerCode { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        public string? Postcode { get; set; }
        public string? ProductCode { get; set; }


        private readonly SelfCareContext _selfcareContext;
        public SignupModel(SelfCareContext selfcareContext)
        {
            _selfcareContext = selfcareContext;

        }
        public void OnGet()
        {

        }

        public IActionResult OnPostSignup([FromForm] string radialValue)
        {
            if (ModelState.IsValid)
            {
                if (ConfirmPassword != Password)
                {
                    ViewData["Response"] = "Passwords must match.";
                    return Page();
                }

                User user = _selfcareContext.Users.Where(u => u.Username == Username || u.Email == Email).FirstOrDefault();
                if (user != null)
                {
                    ViewData["Response"] = "Account already exists with that email/username.";
                    return Page();
                }

                if (radialValue == "practitioner")
                {
                    if (ProductCode == null || ProductCode == String.Empty)
                    {
                        ViewData["Response"] = "Product Code is required.";
                        return Page();
                    }

                    Models.ProductKey productkey = _selfcareContext.ProductKeys.Where(u => u.KeyId == ProductCode).FirstOrDefault();

                    if ((productkey != null) && (_selfcareContext.Practitioners.Where(u => u.ProductId == productkey.ProductId).FirstOrDefault() == null)) //If product key exists and not already claimed
                    {
                        Models.Practitioner newPractitioner = new Models.Practitioner();

                        newPractitioner.ProductId = productkey.ProductId;
                        newPractitioner.FirstName = FirstName;
                        newPractitioner.LastName = LastName;
                        newPractitioner.UserId = 1;

                        try
                        {
                            _selfcareContext.Practitioners.Add(newPractitioner);
                            _selfcareContext.SaveChanges();
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex.ToString());
                            ViewData["Message"] = "An error has occured";
                            return Page();
                        }

                        Models.Practitioner finishedPractitioner = _selfcareContext.Practitioners.Where(u => u.ProductId == productkey.ProductId).FirstOrDefault();

                        if (finishedPractitioner != null)
                        {
                            Models.User newUser = new Models.User();

                            newUser.Username = Username;
                            newUser.Password = Password;
                            newUser.Email = Email;
                            newUser.UserTypeId = (int)Infrastructure.Enums.UserType.Practitioner;
                            newUser.DateUpdated = DateTime.Now;
                            newUser.DateCreated = DateTime.Now;

                            try
                            {
                                _selfcareContext.Users.Add(newUser);
                                _selfcareContext.SaveChanges();
                            }
                            catch (Exception ex)
                            {
                                Console.WriteLine(ex.ToString());
                                ViewData["Message"] = "An error has occured";
                                return Page();
                            }

                            finishedPractitioner.UserId = newUser.UserId;
                            finishedPractitioner.DateUpdated = DateTime.Now;

                            try
                            {
                                _selfcareContext.SaveChanges();
                            }
                            catch (Exception ex)
                            {
                                Console.WriteLine(ex.ToString());
                                ViewData["Message"] = "An error has occured";
                                return Page();
                            }
                            return RedirectToPage("/login");
                        }
                        ViewData["Response"] = "An error occured";
                        return Page();
                    }

                    ViewData["Response"] = $"Product code: {ProductCode} does not match with any account or has already been claimed.";
                    return Page();
                }

                if (radialValue == "patient")
                {
                    if (DateOfBirth == null || PractitionerCode == null || Postcode == null)
                    {
                        ViewData["Response"] = "All patient fields are required.";
                        return Page();
                    }


                    Models.Patient patient = _selfcareContext.Patients.Where(u => u.DateOfBirth == DateOfBirth && u.PostCode == Postcode && u.FirstName == FirstName && u.LastName == LastName).FirstOrDefault();

                    if (patient == null)
                    {
                        ViewData["Response"] = "Could not find matching credentials stored. Message your practitioner for more information.";
                        return Page();
                    }

                    if (PractitionerCode != patient.PractitionerKey)
                    {
                        ViewData["Response"] = "The Account found practitioner code does not match";
                        return Page();
                    }

                    if ((patient != null) && (patient.PractitionerKey == PractitionerCode)) //If patient key exists and key not already claimed
                    {
                        Models.User newUser = new Models.User();

                        newUser.Username = Username;
                        newUser.Password = Password;
                        newUser.Email = Email;
                        newUser.UserTypeId = (int)Infrastructure.Enums.UserType.Patient;
                        newUser.DateUpdated = DateTime.Now;
                        newUser.DateCreated = DateTime.Now;

                        try
                        {
                            _selfcareContext.Users.Add(newUser);
                            _selfcareContext.SaveChanges();
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex.ToString());
                            ViewData["Message"] = "An error has occured.";
                            return Page();
                        }

                        Models.Patient finishedPatient = _selfcareContext.Patients.Where(u => u.PractitionerKey == PractitionerCode).FirstOrDefault();
                        if (finishedPatient != null)
                        {
                            finishedPatient.UserId = newUser.UserId;
                            finishedPatient.DateUpdated = DateTime.Now;

                            try
                            {
                                _selfcareContext.SaveChanges();
                            }
                            catch (Exception ex)
                            {
                                Console.WriteLine(ex.ToString());
                                ViewData["Message"] = "An error has occured.";
                                return Page();
                            }

                            return RedirectToPage("/login");
                        }

                        ViewData["Response"] = "An error occured. Could not find updated patient.";
                        return Page();
                    }

                    ViewData["Response"] = "An error occured. Code might be claimed";
                }
            }

            if (radialValue == null)
            {
                ViewData["Response"] = "You must select practitioner or patient.";
                return Page();
            }

            ViewData["Response"] = "An error occured, the model was not validated";
            return Page();
        }
    }
}

SelfCare/Pages/login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SelfCare.Models;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace SelfCare.Pages
{
    [BindProperties]
    public class LoginModel : PageModel
    {
        private readonly SelfCareContext _selfcareContext;
        
        [Required]
        public string Username { get; set; }
        [Required]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$", ErrorMessage = "Password must contain at least one lowercase letter, one uppercase letter, and one integer.")]
        public string Password { get; set; }


        public LoginModel(SelfCareContext selfcareContext)
        {
            _selfcareContext = selfcareContext;

        }

        public IActionResult OnPostLoginInfo()
        {
            if (ModelState.IsValid)
            {
                User user = _selfcareContext.Users.Where(u => u.Username == Username).Include(u => u.UserType).FirstOrDefault();

                //Validation
                if (user == null) {
                    ViewData["ErrorMessage"] = "Username is incorrect or does not exist, Sign up to create an account.";
                    return Page(); 
                }

                //Process login credentials
                if (user.Password == Password)
                {
                    //Valid User

                    //Set session variables 
                    //For isloggedin, UserId, UserType

                    HttpContext.Session.SetInt32(SessionVariables.SessionKeyUserId, user.UserId);
                    HttpContext.Session.SetString(SessionVariables.SessionKeyLoggedIn, "true");
                    HttpContext.Session.SetInt32(SessionVariables.SessionKeyUserType, user.UserTypeId);

                    if (user.UserTypeId == (int)Infrastructure.Enums.UserType.Patient) {

                        return RedirectToPage("/patient/index");

                    }

                    if (user.UserTypeId == (int)Infrastructure.Enums.UserType.Practitioner)
                    {
                        return RedirectToPage("/practitioner/index");
                    }

                    ViewData["ErrorMessage"] = "Error Occured";
                    return Page();
                    
                }
                else 
                {
                    ViewData["ErrorMessage"] = "Username and password do not match.";
                    return Page();
                }

            } 
            else 
            {
                return Page();
            }
        }
        public void OnGet()
        {
        }
        public void OnPost()
        {
        }
    }
}

SelfCare/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<div class="text-center">
    <h1>Welcome to the Selfcare home page!</h1>
    <b>Enjoy the full range of features we offer</b>
</div>

SelfCare/Pages/Login.cshtml
@page
@model SelfCare.Pages.LoginModel
@{
    <div1>
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <form method="post" asp-page-handler="LoginInfo">
            <p1>Username</p1><br />
            <input asp-for="Username" /><br />
            <span asp-validation-for="Username"></span><br />
            <p2>Password</p2><br />
            <input asp-for="Password" /><br />
            <span asp-validation-for="Password"></span><div id="Error">@ViewData["ErrorMessage"]</div>
            <p3>
                <br />
                <Input type="submit" value="Login">
            </p3>
        </form>
        @section scripts {
            <partial name="_ValidationScriptsPartial" />
        }
        <script>
            // <form id="loginForm" >
            //     <label>Username: </label>
            //         < input type = "text" id = "name" name = "name" required >
            //             <label>Password: </label>
            //                 < input type = "text" id = "password" name = "password" required >
            //                     <div id="Error" > </div>
            //                         < button type = "button" onclick = "validateFormData()" > Login < /button>
            //                             < /form>
            //                                             function validateFormData() {
            //                                                 var username = document.getElementById("name").value
            //                                                 var password = document.getElementById("password").value
            //                                                 var passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$";

            //                                                 if (username != null && password != null)

            // /*                                                 && (password.length() >= 8) && (passwordRegex.test(password))) */
            //                                                 {

            //                                                     postLoginInfo();

            //                                                 } else if (username == null && password == null) {

            //                                                     // document.getElementById("Error").textContent = "Username & Password must not be empty!";

            //                                                 } else if ((password.length() >= 8) && (passwordRegex.test(password))) {

            //                                                     // document.getElementById("Error").textContent = "Password must be longer than 8 Characters & Must contain atleast 1 Uppercase, 1 Lowercase and 1 number!";

            //                                                 } else {

            //                                                     // document.getElementById("Error").textContent = "Error";

            // //                                                 }

            //                                             }

            //                                             function postLoginInfo() {
            //                                                 // var loginData = $("#loginForm").serialize();

            //                                                 $.ajax({
            //                                                     url: '/Login?handler=LoginInfo',
            //                                                     type: 'POST',
            //                                                     data: "test",
            //                                                     async: true,
            //                                                     headers: {
            //                                                         RequestVerificationToken:
            //                                                             $('input:hidden[name="__RequestVerificationToken"]').val()
            //                                                     },
            //                                                     success: function (response) {
            //                                                         $("#response").html(response);
            //                                                     },
            //                                                     error: function (error) {
            //                                                         console.log("Error:", error);
            //                                                     }
            //                                                 });
            //                                             }

        </script>
    </div1>
}

SelfCare/Pages/Signup.cshtml
@page
@model SelfCare.Pages.SignupModel
@{
        <div>
            <form method="post" asp-page-handler="Signup">
                <div>
                    <p1>Email</p1> <p2>Username</p2><br />
                    <input asp-for="Email" /> <input asp-for="Username" /><br />
                    <span asp-validation-for="Email"></span><span asp-validation-for="Username"></span><br />
                </div>

                <div>
                    <p4>Password</p4> <p5>Confirm Password</p5><br />
                    <input asp-for="Password" /> <input asp-for="ConfirmPassword" /><br />
                    <span asp-validation-for="Password"></span><span asp-validation-for="ConfirmPassword"></span><br />
                </div>

                <div>
                    <p4>First Name</p4> <p5>Last Name</p5><br />
                    <input asp-for="FirstName" /> <input asp-for="LastName" /><br />
                    <span asp-validation-for="FirstName"></span><span asp-validation-for="LastName"></span><br />
                </div>

                <div class="radio_container">
                    <input type="radio" id="patient" name="role" onclick="showPatientSection()" />
                    <label for="patient">Patient</label>

                    <input type="radio" id="practitioner" name="role" onclick="showPractitionerSection()" />
                    <label for="practitioner">Practitioner</label>
                </div>

                <div id="patientSection" style="display:none;">
                    <p>Practitioner Code</p>
                    <input asp-for="PractitionerCode" /><br />
                    <span asp-validation-for="PractitionerCode"></span><br />

                    <p>Date Of Birth</p>
                    <input asp-for="DateOfBirth" /><br />
                    <span asp-validation-for="DateOfBirth"></span><br />

                    <p>Postcode</p>
                    <input asp-for="Postcode" /><br />
                    <span asp-validation-for="Postcode"></span><br />
                </div>

                <div id="practitionerSection" style="display:none;">
                    <p>Product Code</p>
                    <input asp-for="ProductCode" /><br />
                    <span asp-validation-for="ProductCode"></span><br />
                </div>

                <div>
                    <br />
                    <input id="radialValue" name="radialValue" type="hidden" value="" />
                    <Input type="submit" value="Sign-up">
                </div>
                <div7>@ViewData["Response"]</div7>
            </form>
        </div>
    @section scripts {
            <partial name="_ValidationScriptsPartial" />
            <script>
                function showPatientSection() {
                    document.getElementById("patientSection").style.display = "block";
                    document.getElementById("practitionerSection").style.display = "none";

                    document.getElementsByName("radialValue")[0].value = "patient";
                }

                function showPractitionerSection() {
                    document.getElementById("practitionerSection").style.display = "block";
                    document.getElementById("patientSection").style.display = "none";

                    document.getElementsByName("radialValue")[0].value = "practitioner";
                }
            </script>
    }
}

SelfCare/Pages/_NoteTablePartial.cshtml
@using SelfCare
@namespace SelfCare.Pages
@model List<SelfCare.Models.Note>

<table>
    <thead>
        <tr>
            <th>Note Id</th>
            <th>Patient Id</th>
            <th>Title</th>
            <th>Body</th>
            <th>Date Updated</th>
            <th>Date Created</th>
        </tr>
    </thead>
    <tbody>
         @foreach (var note in Model)
        {
            <tr>
                <td>@note.NoteId</td>
                <td>@note.PatientId</td>
                <td>@note.Title</td>
                <td>@note.Body</td>
                <td>@note.DateUpdated</td>
                <td>@note.DateCreated</td>
            </tr>
        }
    </tbody>
</table>