SelfCare/Pages/Patient/CreateNote.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SelfCare.Models;
using System.ComponentModel.DataAnnotations;

namespace SelfCare.Pages.Patient
{
    [BindProperties]
    public class CreateNoteModel : PageModel
    {
        [Required]
        public string noteName { get; set; }

        public string description { get; set; }

        private readonly SelfCareContext _selfcareContext;
        public CreateNoteModel(SelfCareContext selfcareContext)
        {
            _selfcareContext = selfcareContext;

        }
        public IActionResult OnGet()
        {
            int userType = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserType) ?? 0;
            string loggedInStatus = HttpContext.Session.GetString(SessionVariables.SessionKeyLoggedIn) ?? "";

            if ((loggedInStatus != "true") || (userType != (int)Infrastructure.Enums.UserType.Patient))
            {

                return RedirectToPage("/login");
            }

            return Page();
        }

        public IActionResult OnPostCreateNote() 
        { 
            if (ModelState.IsValid)
            {
                int userId = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserId) ?? 0;
                if (userId != 0) 
                {
                    Models.Patient patient = _selfcareContext.Patients.Where(p => p.UserId == userId).FirstOrDefault();
                    if (patient != null) 
                    { 
                        Note newNote = new Note();
                        newNote.Title = noteName;
                        newNote.Body = description;
                        newNote.PatientId = patient.PatientId;
                        _selfcareContext.Notes.Add(newNote);
                        _selfcareContext.SaveChanges();
                        return RedirectToPage("/patient/Notes");
                    }
                }
            }

            ViewData["Error"] = "An error has occured if this persists please contact support.";
            return Page();
        }
    }
}

SelfCare/Pages/Patient/EditNote.cshtml.cs
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SelfCare.Models;
using System.Collections.Concurrent;
using System.ComponentModel.DataAnnotations;

namespace SelfCare.Pages.Patient
{
    [BindProperties]
    public class EditNoteModel : PageModel
    {
        public Models.Note editNote { get; set; }

        [Required]
        public string noteName { get; set; }

        public string noteBody { get; set; }
        public int noteId { get; set; }

        private readonly SelfCareContext _selfcareContext;
        public EditNoteModel(SelfCareContext selfcareContext)
        {
            _selfcareContext = selfcareContext;

        }
        public IActionResult OnGet()
        {
            int userType = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserType) ?? 0;
            string loggedInStatus = HttpContext.Session.GetString(SessionVariables.SessionKeyLoggedIn) ?? "";
                
            if ((loggedInStatus != "true") || (userType != (int)Infrastructure.Enums.UserType.Patient))
            {

                return RedirectToPage("/login");
            }

            return RedirectToPage("/patient/Notes"); //As This page isnt meant to be onget'd it redirects requests to notes
        }

        public IActionResult OnPost(int? editNoteId) // editNoteId is passed from the form via the https link
        { 
            if (editNoteId == null)
            {
                return RedirectToPage("/patient/Notes"); // If no note provided redirect them back
            }

            int userId = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserId) ?? 0;

            if (userId != 0)
            {
                Models.Patient patient = _selfcareContext.Patients.Where(p => p.UserId == userId).FirstOrDefault(); //Get the patient from userid

                //Get the note that matches with the noteId and also belongs to the patient logged in
                editNote = _selfcareContext.Notes.Where(x => x.NoteId == editNoteId && x.PatientId == patient.PatientId).FirstOrDefault(); 
            }

            if (editNote == null) //If no notes were found send them to back to the patients
            {
                return RedirectToPage("/patient/Notes");
            }
            
            //Set the notename as the note that was founds title
            noteName = editNote.Title;
            //Set the notebody as the notes body
            noteBody = editNote.Body;
            //return the page with the populated variables
            return Page();
        }
        public IActionResult OnPostEditNote() //If the use clicks save
        {
            if (ModelState.IsValid) //Make sure the restrictions on the variables are enforced and are valid
            {
                int userId = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserId) ?? 0;

                if (userId != 0)
                {
                    Models.Patient patient = _selfcareContext.Patients.Where(p => p.UserId == userId).FirstOrDefault();

                    if (patient != null)
                    {
                        //Get the note from using the note id
                        var noteToUpdate = _selfcareContext.Notes.Where(x => x.NoteId == noteId).FirstOrDefault();
                        
                        //If the note is populated
                        if (noteToUpdate != null)
                        {
                            //Set the notes properties to the new ones provided by the form and set the updated time to current system time
                            noteToUpdate.Title = noteName;
                            noteToUpdate.Body = noteBody;
                            noteToUpdate.DateUpdated = DateTime.Now;
                            //Save the changed object in the database
                            _selfcareContext.SaveChanges();
                            ViewData["SaveResponse"] = "Saved";
                            return Page();
                        }
                    }
                }
            }

            ViewData["Error"] = "An error has occured if this persists please contact support.";
            return Page();
        }
    }
}

SelfCare/Pages/Patient/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SelfCare.Pages.Patient
{
    public class PatientModel : PageModel
    {
        public IActionResult OnGet()
        {
            int userType = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserType) ?? 0;
            string loggedInStatus = HttpContext.Session.GetString(SessionVariables.SessionKeyLoggedIn) ?? "";

            if ((loggedInStatus != "true") || (userType != (int)Infrastructure.Enums.UserType.Patient))
            {

                return RedirectToPage("/login");
            }

            return Page();
        }
    }
}

SelfCare/Pages/Practitioner/CreateGp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SelfCare.Models;
using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Metrics;

namespace SelfCare.Pages.Practitioner
{
    [BindProperties] //The variables on the webpage bind them to the variables on the controller and their requirements
    public class AddGpModel : PageModel
    {
        private readonly SelfCareContext _selfcareContext;

        [Required]
        public string Name { get; set; }
        [Required]
        public string Address1 { get; set; }
        [Required]
        public string Address2 { get; set; }
        //Not required
        public string? Address3 { get; set; }
        [Required]
        public string Town { get; set; }
        [Required]
        public string County { get; set; }
        [Required]
        public string Postcode { get; set; }
        [Required]
        public string Country { get; set; }

        public AddGpModel(SelfCareContext selfcareContext) //Constructor
        {
            _selfcareContext = selfcareContext;

        }

        public IActionResult OnPostCreateGP()
        {
            if (ModelState.IsValid) //If the form sent in the post has the correct variable standards
            {
                Models.Gp newGp = new Models.Gp(); //Generate a new GP and populate its data
                newGp.Name = Name;
                newGp.Address1 = Address1;
                newGp.Address2 = Address2;
                newGp.Address3 = Address3;
                newGp.Town = Town;
                newGp.County = County;
                newGp.Country = Country;
                newGp.PostCode = Postcode;

                try
                {
                    _selfcareContext.Gps.Add(newGp); //Add the new GP object into the table stored in server memory
                    _selfcareContext.SaveChanges(); //Save the data in the server memory to the SQL database
                } catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString()); //If an error occured write the error in the page's console
                    ViewData["Message"] = "An error has occured";
                    return Page();
                }
                //Show success with GP name for clarification
                ViewData["Response"] = $"Successfully added {newGp.Name} as a GP, Manage your GP's on the GP Page.";
            }
            return Page();
        }
        public IActionResult OnGet()
        {
            int userType = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserType) ?? 0;
            string loggedInStatus = HttpContext.Session.GetString(SessionVariables.SessionKeyLoggedIn) ?? "";

            if ((loggedInStatus != "true") || (userType != (int)Infrastructure.Enums.UserType.Practitioner))
            {

                return RedirectToPage("/login");
            }

            return Page();
        }
    }
}

SelfCare/Pages/Practitioner/CreatePatient.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SelfCare.Models;
using System.ComponentModel.DataAnnotations;

namespace SelfCare.Pages.Practitioner
{
    [BindProperties]
    public class CreatePatientModel : PageModel
    {


        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public DateOnly DateOfBirth { get; set; }
        [Required]
        public string Address1 { get; set; }
        [Required]
        public string Address2 { get; set; }
        public string? Address3 { get; set; }
        [Required]
        public string Town { get; set; }
        [Required]
        public string County { get; set; }
        [Required]
        public string Postcode { get; set; }
        [Required]
        public string Country { get; set; }

        public DateOnly? ReferalDate { get; set; }
        public string? NhsId { get; set; }
        public int? GpId { get; set; }

        private readonly SelfCareContext _selfcareContext;

        public CreatePatientModel(SelfCareContext selfcareContext)
        {
            _selfcareContext = selfcareContext;

        }
        public IActionResult OnPostCreatePatient()
        {
            if (ModelState.IsValid)
            {
                if ((GpId != null) && (!(_selfcareContext.Gps.Any(u => u.Gpid == GpId))))
                {
                    ViewData["Response"] = "Incorrect GP Id or GP Doesnt Exist";
                    return Page();
                }

                Models.Patient newPatient = new Models.Patient();

                int userId = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserId) ?? 0;

                Models.Practitioner practitioner = _selfcareContext.Practitioners.Where(u => u.UserId == userId).FirstOrDefault();

                newPatient.FirstName = FirstName;
                newPatient.LastName = LastName;
                newPatient.DateOfBirth = DateOfBirth;
                newPatient.Address1 = Address1;
                newPatient.Address2 = Address2;
                newPatient.Address3 = Address3;
                newPatient.Town = Town;
                newPatient.County = County;
                newPatient.Country = Country;
                newPatient.PostCode = Postcode;
                newPatient.ReferalDate = ReferalDate;
                newPatient.Nhsid = NhsId;
                newPatient.Gpid = GpId;
                newPatient.PractitionerId = practitioner.PractitionerId;
                newPatient.PractitionerKey = Guid.NewGuid();

                _selfcareContext.Patients.Add(newPatient);
                _selfcareContext.SaveChanges();

                //Show success and Practitioner Key
                ViewData["Response"] = $"You Practitioner Key is :- {newPatient.PractitionerKey}";

                ModelState.Clear();


            }
            return Page();
        }
        public IActionResult OnGet()
        {
            int userType = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserType) ?? 0;
            string loggedInStatus = HttpContext.Session.GetString(SessionVariables.SessionKeyLoggedIn) ?? "";
            int userId = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserId) ?? 0;

            Models.Practitioner practitioner = _selfcareContext.Practitioners.Where(u => u.UserId == userId).FirstOrDefault();

            if ((loggedInStatus != "true") || (userType != (int)Infrastructure.Enums.UserType.Practitioner) || (practitioner == null))
            {

                return RedirectToPage("/login");
            }

            return Page();
        }
    }
}

SelfCare/Pages/Practitioner/GPs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SelfCare.Models;

namespace SelfCare.Pages.Practitioner
{
    public class GPsModel : PageModel
    {
        public List<Gp> Gps { get; set; } //Generate an empty list of the class GP

        private readonly SelfCareContext _selfcareContext;
        public GPsModel(SelfCareContext selfcareContext)
        {
            _selfcareContext = selfcareContext;

        }
        public IActionResult OnGet()
        {
            int userType = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserType) ?? 0;
            string loggedInStatus = HttpContext.Session.GetString(SessionVariables.SessionKeyLoggedIn) ?? "";
            int userId = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserId) ?? 0;

            if ((loggedInStatus != "true") || (userType != (int)Infrastructure.Enums.UserType.Practitioner))
            {

                return RedirectToPage("/login");
            }

            Gps = _selfcareContext.Gps.ToList();

            return Page();
        }
        public IActionResult OnPostDeleteGp([FromForm] int Gpid, [FromForm] string Gpname) 
        {
            
            _selfcareContext.Gps.Where(u => u.Gpid == Gpid).ExecuteDelete(); //Find a GP with the same Id as the one provided by the form and delete it 
            Gps = _selfcareContext.Gps.ToList(); //Repopulate the GP list so the page doesnt break when the onpost handler is sent back
            ViewData["Message"] = $"Successfully Deleted {Gpname}";
            return Page();  
        }

    }
}

SelfCare/Pages/Practitioner/Patients.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SelfCare.Models;

namespace SelfCare.Pages.Practitioner
{
    public class PatientsModel : PageModel
    {
        public List<Models.Patient> Patients { get; set; }

        private readonly SelfCareContext _selfcareContext;
        public PatientsModel(SelfCareContext selfcareContext)
        {
            _selfcareContext = selfcareContext;

        }
        public IActionResult OnGet()
        {
            int userType = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserType) ?? 0;
            string loggedInStatus = HttpContext.Session.GetString(SessionVariables.SessionKeyLoggedIn) ?? "";

            if ((loggedInStatus != "true") || (userType != (int)Infrastructure.Enums.UserType.Practitioner))
            {

                return RedirectToPage("/login");
            }

            PopulatePatients();

            return Page();
        }

        private void PopulatePatients()
        {
            int userId = HttpContext.Session.GetInt32(SessionVariables.SessionKeyUserId) ?? 0;
            Models.Practitioner practitioner = _selfcareContext.Practitioners.Where(x => x.UserId == userId).FirstOrDefault();
            Patients = _selfcareContext.Patients.Include(p => p.Gp).Where(u => u.PractitionerId == practitioner.PractitionerId).ToList();
        }

        public IActionResult OnPostDeletePatient([FromForm] int patientId, [FromForm] string patientName)
        {

            _selfcareContext.Patients.Where(u => u.PatientId == patientId).ExecuteDelete();
            PopulatePatients();
            ViewData["Message"] = $"Successfully Deleted {patientName}";
            return Page();
        }

    }
}

SelfCare/Pages/Practitioner/CreateGp.cshtml
@page
@model SelfCare.Pages.Practitioner.AddGpModel
@{
    <form method="post" asp-page-handler="CreateGP">
        <div>
            <p>Name Country</p><br />
            <input asp-for="Name" /> <input asp-for="Country" /><br />
            <span asp-validation-for="Name"></span><span asp-validation-for="Country"></span><br />
        </div>

        <div>
            <p>Address1 Address2 Address3 (Optional)</p><br />
            <input asp-for="Address1" /> <input asp-for="Address2" /> <input asp-for="Address3" /><br />
            <span asp-validation-for="Address1"></span><span asp-validation-for="Address2"></span><br />
        </div>

        <div>
            <p>Town County Postcode</p><br />
            <input asp-for="Town" /> <input asp-for="County" /> <input asp-for="Postcode" /><br />
            <span asp-validation-for="Town"></span><span asp-validation-for="County"></span><span asp-validation-for="Postcode"></span><br />
        </div>

        <div>
            <br />
            <Input type="submit" value="Create GP">
        </div>
        <div>@ViewData["Response"]</div>
    </form>
    @section scripts {
        <partial name="_ValidationScriptsPartial" />
    }
}

SelfCare/Pages/Practitioner/CreatePatient.cshtml
@page
@model SelfCare.Pages.Practitioner.CreatePatientModel
@{
    <form method="post" asp-page-handler="CreatePatient">
        <div>
            <p>First Name Last Name Date Of Birth</p><br />
            <input asp-for="FirstName" /> <input asp-for="LastName" /> <input asp-for="DateOfBirth" /><br />
            <span asp-validation-for="FirstName"></span><span asp-validation-for="LastName"></span><span asp-validation-for="DateOfBirth"></span><br />
        </div>

        <div>
            <p>Address1 Address2 Address3 (Optional)</p><br />
            <input asp-for="Address1" /> <input asp-for="Address2" /> <input asp-for="Address3" /><br />
            <span asp-validation-for="Address1"></span><span asp-validation-for="Address2"></span><br />
        </div>

        <div>
            <p>Town County Postcode</p><br />
            <input asp-for="Town" /> <input asp-for="County" /> <input asp-for="Postcode" /><br />
            <span asp-validation-for="Town"></span><span asp-validation-for="County"></span><span asp-validation-for="Postcode"></span><br />
        </div>

        <div>
            <p>Country</p><br />
            <input asp-for="Country" /><br />
            <span asp-validation-for="Country"></span><br />

        </div>

        <div>
            <p>Referal Date (Optional) NHSId (Optional) GP Id(Optional)</p><br />
            <input asp-for="ReferalDate" /> <input asp-for="NhsId" /><input asp-for="GpId" /><br />
            <span asp-validation-for="ReferalDate"></span><br />
        </div>

        <div>
            <br />
            <Input type="submit" value="Create Patient">
        </div>
        <div>@ViewData["Response"]</div>
    </form>
    @section scripts {
        <partial name="_ValidationScriptsPartial" />
    }
}

SelfCare/Pages/Practitioner/GPs.cshtml
@page
@model SelfCare.Pages.Practitioner.GPsModel

@{
    <div>
        @foreach (var gp in Model.Gps)
        {
            <div2>
                <h1>
                    @gp.Name - Created @gp.DateCreated     
                    <form method="post">
                        <input type="hidden" name="Gpid" value="@gp.Gpid" />
                        <input type="hidden" name="Gpname" value="@gp.Name" />
                        <button type="submit" asp-page-handler="DeleteGp">Delete</button>
                    </form>
                </h1>

                <b1>
                    Id: @gp.Gpid PostCode: @gp.PostCode Address: @gp.Address1 @gp.Address2 @gp.Address3 Town: @gp.Town County: @gp.County Country: @gp.Country
                </b1>
            </div2>
        }
    </div>
    @if (ViewData["Message"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewData["Message"]");
            };
        </script>
    }
}

SelfCare/Pages/Practitioner/Index.cshtml
@page
@model SelfCare.Pages.Practitioner.IndexModel
@{
    <h1>You're A Practitioner</h1>
    <a asp-page="/practitioner/Gps">GPs</a>
    <br />
    <br />
    <a asp-page="/practitioner/CreateGp">Create GP</a>
    <br />
    <br />
    <a asp-page="/practitioner/CreatePatient">Create Patient</a>
    <br />
    <br />
}

SelfCare/Pages/Practitioner/PatientView.cshtml
@page "/practitioner/patientview/{patientId}"
@model SelfCare.Pages.Practitioner.PatientViewModel
@{
    <div>
        @foreach (var note in Model.notes)
        {
            <div>
                <h1>
                    @note.Title - Created @note.DateCreated
                </h1>
                <p>
                    @if (note.Body.Length >=25)
                    {
                        @note.Body.Substring(0, 25);
                        <span>{Click to view more...}</span>
                    }
                    else
                    {
                        @note.Body
                    }
                    <form method="post" asp-page="/practitioner/viewnote">
                        <input name="NoteId" type="hidden" value="@note.NoteId" />
                        <button type="submit">Click to view</button>
                    </form>
                </p>
            </div>
        }
    </div>
    @if (ViewData["Message"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewData["Message"]");
            };
        </script>
    }
}

SelfCare/Pages/Practitioner/Patients.cshtml
@page
@model SelfCare.Pages.Practitioner.PatientsModel
@{
    <style>
        .patientContainer {
            display: flex;
            align-items: center;
            gap: 20px;
            padding: 20px;
            border: 2px solid #ccc;
            border-radius: 10px;
            transition: box-shadow 0.3s ease-in-out;
        }

            .patientContainer:hover {
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            }

        .fieldLabel{
            font-weight:bold;
            padding-right:5px !important;
        }

        .patientBox {
            display: block;
            cursor: pointer;
            text-decoration: none;
            color: black !important;
            width: 100%;
            position: relative;
        }

            .patientBox h1,
            .patientBox span,
            .patientBox b {
                margin: 0;
                padding: 0;
                font-family: 'OpenDyslexic', cursive, sans-serif !important;
            }

        .hovertip {
            display: none;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: #fff;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
        }

        .patientBox:hover .hovertip {
            display: block !important;

        }

        .deleteButton form {
            display: inline-block !important;
            vertical-align: middle !important;
        }

            .deleteButton form button {
                background-color: #ff6666 !important;
                color: #fff !important;
                padding: 10px 20px !important;
                border: none !important;
                border-radius: 5px !important;
                transition: background-color 0.3s ease-in-out !important;
            }

                .deleteButton form button:hover {
                    background-color: #ff4d4d !important;
                }

        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(5, 34, 33, 0.8);
        }

        .modal-content {
            font-family: "OpenDyslexic", sans-serif;
            background-color: #d5e3e3;
            margin: 15% auto;
            padding: 20px;
            border: 2px solid #888;
            border-radius: 10px;
            width: 280px;
        }

        .modal-content button{
            margin:10px;
        }
    </style>
    <div>
        <div id="modal" class="modal">
            <div class="modal-content">
                <p>Are you sure you want to delete?</p>
                <button id="confirmYes">Yes</button>
                <button id="confirmNo">No</button>
            </div>
        </div>
        @foreach (var patient in Model.Patients)
        {
            <div class="patientContainer">
                <a class="patientBox" href="/practitioner/patientview/@patient.PatientId">
                    <div style="display: flex; align-items: center;">
                        <span style="font-size: 3em;">
                            @patient.FirstName @patient.LastName
                        </span>
                        <span style="margin-left:10px">- Created @patient.DateCreated</span>
                    </div>
                    <br />
                    @if (patient.Gp != null)
                        {
                        <div style="margin-right:30px;display:inline"><span class="fieldLabel">GP's Name:</span><span>@patient.Gp.Name</span></div>
                        <div style="margin-right:30px;display:inline"><span class="fieldLabel">GP's ID:</span><span>@patient.Gpid</span></div>
                        }
                        
                    <p>
                        <span class="fieldLabel">PostCode:</span> @patient.PostCode
                        <span class="fieldLabel" style="margin-left:20px">Address:</span> @patient.Address1 @patient.Address2 @patient.Address3
                        <span class="fieldLabel" style="margin-left:20px">Town:</span> @patient.Town
                        <span class="fieldLabel" style="margin-left:20px">County:</span> @patient.County
                        <span class="fieldLabel" style="margin-left:20px">Country:</span> @patient.Country
                    </p>
                    <div class="hovertip">
                        View @patient.FirstName's Notes
                    </div>
                </a>
                <div class="deleteButton">
                    <form id="deleteForm_@patient.PatientId" method="post" asp-page-handler="DeletePatient">
                        <input type="hidden" name="patientid" value="@patient.PatientId" />
                        <input type="hidden" name="patientname" value="@patient.FirstName @patient.LastName" />
                        <button id="deleteButton_@patient.PatientId" type="button" data-formid="@patient.PatientId" >Delete</button>
                    </form>
                </div>
            </div>
        }
    </div>

    @if (ViewData["Message"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewData["Message"]");
            };
        </script>
    }

    <script type="text/javascript">
        window.onload = function () {
        @foreach (var patient in Model.Patients)
        {
            <text>
                    document.getElementById("deleteButton_@patient.PatientId").addEventListener("click", function () {
                        document.getElementById("modal").style.display = "block";
                        debugger;
                        var formId = this.getAttribute("data-formid");
                        
                        document.getElementById("confirmYes").setAttribute("data-formid", formId);
                    });
            </text>
        }

                document.getElementById("confirmYes").addEventListener("click", function () {
                    debugger;
                    var formId = this.getAttribute("data-formid");
                    var jam = "deleteForm_" + formId;
                    document.getElementById(jam).submit();
                });

            document.getElementById("confirmNo").addEventListener("click", function () {
                document.getElementById("modal").style.display = "none";
            });
        };
    </script>
}

SelfCare/Pages/Practitioner/ViewNote.cshtml
@page
@model SelfCare.Pages.Practitioner.ViewNoteModel
@{
    <p1>Note's Name</p1>
    <br />
    <textarea asp-for="noteName"></textarea>
    <br />

    <span asp-validation-for="noteName"></span>
    <br />

    <textarea asp-for="noteBody"></textarea>
    @if (@Model.Viewnote.DateUpdated != Model.Viewnote.DateCreated)
    {
        <span>Last Editted:</span>

        <span>@Model.Viewnote.DateUpdated</span>
    }
    else {
        <span>Created:</span>
        <span>@Model.Viewnote.DateCreated</span>
    }
}